import {
  COLOR_CYAN_BLUE,
  COLOR_DARK_GREEN,
  COLOR_ORANGE_YELLOW,
} from "./COLORS";

export const ORDER_STATUS_PENDING = "Pending";
export const ORDER_STATUS_PICKED = "Picked";
export const ORDER_STATUS_READY = "Printed";

// COLOURS ORDER STATUS
export const COLOR_ORDER_STATUS_PENDING = COLOR_ORANGE_YELLOW;
export const COLOR_ORDER_STATUS_PICKED = COLOR_DARK_GREEN;
export const COLOR_ORDER_STATUS_READY = COLOR_CYAN_BLUE;
